### PR TITLE
Added integration with ft_data

### PR DESCRIPTION
**Pull request by willpearse**
You can now use EPMC, bioRxiv, and grab from an existing ```ft``` or ```ft_data``` object.

Let me know what you think :p

### CODE REVIEW

**Comment by sckott** [comment]
thanks for this @willpearse I'll pull it down and play locally for a bit

**Comment by sckott** [comment]
A few things:

### dispatch

I'd prefer if instead of doing dispatch on classes internally within `ft_get_si()` that you follow what we've done in the package thus far, e.g, 

```r
ft_get_si <- function(x, ...) UseMethod("ft_get_si")

# for DOI inputs, etc.
ft_get_si.character <- function(x, ...) {
  ...
}

# for output from ft_get
ft_get_si.ft_data <- function(x, ...) {
  ...  
}

# for output from ft_search
ft_get_si.ft <- function(x, ...) {
  ...
}

... # whatever else you need, e.g,. lists
```

Is that okay with you? Anything against that approach?

### a bit of cleanup

Could you separate out the plugins for each source into a separate file?  And the man file stuff is getting pretty big. Can you put whatever makes sense (perhaps the details section and the list of sources) into a file in `man-roxygen` dir and call it via `@template`

**Comment by willpearse** [comment]
Thanks for this. If that's what you'd prefer, that's what I'll do - I'll try and get to this by the end of the week.

**Comment by sckott** [comment]
Thanks, and sorry for all the suggested changes

**Comment by willpearse** [comment]
It's no problem!...

**Comment by willpearse** [comment]
Hopefully I've done what you want. I had to manually merge the branches; there was a NAMESPACE issue that looked like an issue with ```roxygen```. There are some warnings on the package if you ```check --as-cran```, but they look to be about the code you're working on right now.

**Comment by sckott** [comment]
@willpearse thanks! LGTM

**Comment by willpearse** [comment]
No worries :D

**Pull request merged**
