### PR TITLE
Added DataDRYAD support

### PR DESCRIPTION
**Pull request by willpearse**
You can now download from dryad using `ft_get_si`. Includes a minimal test.

## Description
Very small change. Needs reserved URL encoding (a lot of dryad files use spaces, etc., in filenames)

## Related Issue
None.

## Example
data <- read.table(ft_get_si("10.5061/dryad.55610", "Data (revised).txt"), header=T, sep='\t')

### CODE REVIEW

**Comment by sckott** [comment]
nice @willpearse - 

can you add more tests though?  looks like there's only 1 line of test for Dryad

**Comment by willpearse** [comment]
Done

**Comment by sckott** [comment]
first, apologies, but we aren't running tests on travis, and we probably should be - will remedy that , but testing locally

- the tests on line 9, 12, 13, 14, 15, 31, 32, 33, 38, 39, 40,  of `test-ft_get_si` fail

**Comment by sckott** [comment]
forgot about this, thoughts @willpearse ?

**Comment by willpearse** [comment]
Thanks - I'll take a look at this. Sorry for the delay - I've been on honeymoon (hooray!) so I've been a little slow of late :D

**Comment by sckott** [comment]
congrats on marriage 🎉

**Comment by sckott** [comment]
@willpearse closing this, since we're moving supp stuff to a new pkg

**Pull request closed without merging**
