### PR TITLE
Biorxiv

### PR DESCRIPTION
**Pull request by emhart**
Integrated search functionality for `biorxiv` package into `ft_search()` with appropriate plugin. Fix for issue #20

### CODE REVIEW

**Comment by sckott** [comment]
@emhart hmmm, i think you meant to submit this to `master`  branch? or no?

**Comment by sckott** [comment]
@emhart i had some changes i forgot to push to master, which I just did, so if you meant to push to master, merge master in first cause I have some commits from this morning

**Comment by emhart** [comment]
I wasn't sure if you wanted to have it on a test branch or not, but I'll re-merge and send a PR to master later today.

**Comment by sckott** [comment]
master is fine i think since i don't think that many people use this yet

**Pull request closed without merging**
